# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_add_student_option_ase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=40, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('I', 'Inconnu')], max_length=3, verbose_name='Genre')),
                ('birth_date', models.DateField(blank=True, verbose_name='Date de naissance')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='Rue')),
                ('pcode', models.CharField(max_length=4, verbose_name='Code postal')),
                ('city', models.CharField(max_length=40, verbose_name='Localité')),
                ('tel', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=40, verbose_name='Portable')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                ('avs', models.CharField(blank=True, max_length=15, verbose_name='No AVS')),
                ('handicap', models.BooleanField(default=False)),
                ('exemption_ecg', models.BooleanField(default=False)),
                ('date_confirmation_mail', models.DateField(auto_now_add=True, verbose_name='Mail de confirmation')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrev', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AsaAsscCandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stages.Candidate')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.Corporation', verbose_name='Employeur')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.CorpContact', verbose_name='FEE/FPP')),
            ],
            bases=('stages.candidate',),
        ),
        migrations.CreateModel(
            name='AseCandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stages.Candidate')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.Corporation', verbose_name='Employeur')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.CorpContact', verbose_name='FEE/FPP')),
            ],
            bases=('stages.candidate',),
        ),
        migrations.CreateModel(
            name='EdePECandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stages.Candidate')),
                ('registration_form', models.BooleanField(default=False)),
                ('certificate_of_payement', models.BooleanField(default=False)),
                ('police_record', models.BooleanField(default=False)),
                ('cv', models.BooleanField(default=False)),
                ('certif_of_cfc', models.BooleanField(default=False)),
                ('certif_of_800h', models.BooleanField(default=False)),
                ('reflexive_text', models.BooleanField(default=False)),
                ('proc_admin_ext', models.BooleanField(default=False)),
                ('work_certificate', models.BooleanField(default=False)),
                ('marks_certificate', models.BooleanField(default=False)),
                ('deposite_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date dépôt dossier')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.Corporation', verbose_name='Employeur')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.CorpContact', verbose_name='FEE/FPP')),
            ],
            bases=('stages.candidate',),
        ),
        migrations.CreateModel(
            name='EdePSCandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stages.Candidate')),
                ('registration_form', models.BooleanField(default=False)),
                ('certificate_of_payement', models.BooleanField(default=False)),
                ('police_record', models.BooleanField(default=False)),
                ('cv', models.BooleanField(default=False)),
                ('certif_of_cfc', models.BooleanField(default=False)),
                ('certif_of_800h', models.BooleanField(default=False)),
                ('reflexive_text', models.BooleanField(default=False)),
                ('proc_admin_ext', models.BooleanField(default=False)),
                ('work_certificate', models.BooleanField(default=False)),
                ('marks_certificate', models.BooleanField(default=False)),
                ('deposite_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date dépôt dossier')),
            ],
            bases=('stages.candidate',),
        ),
        migrations.AddField(
            model_name='candidate',
            name='district',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.District'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.Option'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.Section'),
        ),
    ]
