# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_add_student_option_ase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='option_ase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.Option'),
        ),
    ]
