# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_ame=Add_Candidate_model'),
    ]

    operations = [
    ]
