# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_ame=Add_Candidate_Model'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Admis'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='file_resp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_file_exp', to='stages.Teacher', verbose_name='Exp. dossier'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_resp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.Teacher', verbose_name='Exp. entretien'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.BooleanField(default=False),
        ),
    ]
