# Generated by Django 2.0.1 on 2018-02-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_student_birthdate_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='report_sem_1',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date envoi bull. sem1'),
        ),
        migrations.AddField(
            model_name='student',
            name='report_sem_2',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date envoi bull. sem2'),
        ),
        migrations.AlterField(
            model_name='period',
            name='section',
            field=models.ForeignKey(limit_choices_to={'name__startswith': 'MP'}, on_delete=django.db.models.deletion.PROTECT, to='stages.Section', verbose_name='Filière'),
        ),
    ]
