# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_add_corp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpcontact',
            name='sections',
            field=models.ManyToManyField(blank=True, to='stages.Section'),
        ),
    ]
