# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_corpcontact_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpcontact',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Courriel'),
        ),
    ]
