# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_ame=Add_EdsCandidate_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='tel',
        ),
        migrations.AddField(
            model_name='candidate',
            name='certif_of_800h',
            field=models.BooleanField(default=False, verbose_name='Attest. 800h.'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='certif_of_cfc',
            field=models.BooleanField(default=False, verbose_name='CFC'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='certificate_of_payement',
            field=models.BooleanField(default=False, verbose_name='Attest. paiement'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='contract',
            field=models.BooleanField(default=False, verbose_name='Contrat valide'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.Corporation', verbose_name='Employeur'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.BooleanField(default=False, verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='deposite_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date dépôt dossier'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='examination_result',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Points examen'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='file_result',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Points dossier'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.CorpContact', verbose_name='FEE/FPP'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date entretien prof.'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_result',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Points entretien prof.'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_room',
            field=models.CharField(blank=True, max_length=50, verbose_name="Salle d'entretien prof."),
        ),
        migrations.AddField(
            model_name='candidate',
            name='marks_certificate',
            field=models.BooleanField(default=False, verbose_name='Bull. notes'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='police_record',
            field=models.BooleanField(default=False, verbose_name='Casier judic.'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='proc_admin_ext',
            field=models.BooleanField(default=False, verbose_name='Insc. autre école'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='promise',
            field=models.BooleanField(default=False, verbose_name="Promesse d'eng."),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reflexive_text',
            field=models.BooleanField(default=False, verbose_name='Texte réflexif'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='registration_form',
            field=models.BooleanField(default=False, verbose_name="Formulaire d'inscription"),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_result_mark',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Note finale'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_result_points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Total points'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_certificate',
            field=models.BooleanField(default=False, verbose_name='Certif. de travail'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_confirmation_mail',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Mail de confirmation'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='district',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.District', verbose_name='Canton'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='option',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='section',
            field=models.CharField(choices=[('ASA', 'Aide en soin et accompagnement AFP'), ('ASE', 'Assist. socio-éducatif-ve CFC'), ('ASSC', 'Assist. en soin et santé communautaire CFC'), ('EDE', "Educ. de l'enfance, dipl. ES"), ('EDS', 'Educ. social-e, dipl. ES')], max_length=10, verbose_name='Filière'),
        ),
    ]
