# Generated by Django 2.0.1 on 2018-02-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_extend_student_avs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='rôle')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpcontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.CorpContact')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.Role')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.Student')),

            ],
        ),

        migrations.AlterField(
            model_name='period',
            name='section',
            field=models.ForeignKey(limit_choices_to={'name__startswith': 'MP'}, on_delete=django.db.models.deletion.PROTECT, to='stages.Section', verbose_name='Filière'),
        ),

        migrations.AddField(
            model_name='corpcontact',
            name='roles_ede',
            field=models.ManyToManyField(blank=True, to='stages.Role'),
        ),
        migrations.AddField(
            model_name='student',
            name='expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='rel_expert', to='stages.CorpContact', verbose_name='expert'),
        ),
        migrations.AddField(
            model_name='student',
            name='fpp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='rel_fpp', to='stages.CorpContact', verbose_name='fpp'),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='rel_mentor', to='stages.CorpContact', verbose_name='mentor'),
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='rel_supervisor', to='stages.CorpContact', verbose_name='superviseur'),
        ),
        migrations.AlterModelOptions(
            name='corpcontact',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Contact'},
        ),

    ]
