# Generated by Django 1.9.1 on 2016-01-18 12:37
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_corporation_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpcontact',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
    ]
