# Generated by Django 1.9.1 on 2016-01-19 11:35
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_corpcontact_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Prioritaire'),
        ),
    ]
