# Generated by Django 1.9.1 on 2016-01-29 17:52
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0008_availability_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ('-availability__period',), 'verbose_name': 'Stage'},
        ),
        migrations.AddField(
            model_name='student',
            name='archived_text',
            field=models.TextField(blank=True),
        ),
    ]
