# Generated by Django 2.0.1 on 2018-03-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_corpcontact_corp_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEDESession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=10, verbose_name='saison')),
            ],
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Banque (Nom et ville)'),
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='ccp',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Compte de chèque postal'),
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='clearing',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='No clearing'),
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='fields_of_interest',
            field=models.TextField(blank=True, verbose_name="Domaines d'intérêts"),
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=21, verbose_name='iban'),
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='qualification',
            field=models.TextField(blank=True, verbose_name='Titres obtenus'),
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='city',
            field=models.CharField(blank=True, max_length=40, verbose_name='Localité'),
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='pcode',
            field=models.CharField(blank=True, max_length=4, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rue'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_exam',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_internal_expert', to='stages.Teacher', verbose_name='Expert interne'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.FloatField(blank=True, default=0, verbose_name='note'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_referent', to='stages.Teacher', verbose_name='Référent avant-projet'),
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='salle'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.TextField(blank=True, verbose_name='Résumé TD'),
        ),
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.TextField(blank=True, verbose_name='Titre du TD'),
        ),
        migrations.AddField(
            model_name='student',
            name='training_referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_training_referent', to='stages.Teacher', verbose_name='Référent de stage'),
        ),
        migrations.AlterField(
            model_name='period',
            name='section',
            field=models.ForeignKey(limit_choices_to={'name__startswith': 'MP'}, on_delete=django.db.models.deletion.PROTECT, to='stages.Section', verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='student',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_expert', to='stages.CorpContact', verbose_name='Expert externe'),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.ExamEDESession'),
        ),
    ]
