# Generated by Django 1.10 on 2016-08-31 14:48
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_student_archived_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.Klass', verbose_name='Classe'),
        ),
    ]
