# Generated by Django 2.0.1 on 2018-03-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0010_add_fields_to_Sudent_&_CorpContact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examedesession',
            options={'verbose_name': "Session d'examen EDE"},
        ),
        migrations.AddField(
            model_name='corpcontact',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de naissance'),
        ),
    ]
