# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0010_nullable_student_klass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(max_length=10, verbose_name='Civilité')),
                ('first_name', models.CharField(max_length=40, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=40, verbose_name='Nom')),
                ('abrev', models.CharField(max_length=10, verbose_name='Sigle')),
                ('birth_date', models.DateField(blank=True, verbose_name='Date de naissance')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                ('contract', models.CharField(max_length=20, verbose_name='Contrat')),
                ('rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name="Taux d'activité")),
                ('ext_id', models.IntegerField(blank=True, null=True)),
                ('previous_report', models.IntegerField(default=0, verbose_name='Report précédent')),
                ('next_report', models.IntegerField(default=0, verbose_name='Report suivant')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.AddField(
            model_name='klass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.Teacher', verbose_name='Maître de classe'),
        ),
    ]
