# Generated by Django 2.0.1 on 2018-04-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0012_added_date_fields_for_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisionBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(default=0, verbose_name='période')),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.Student', verbose_name='étudiant')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.CorpContact', verbose_name='superviseur')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'facture de supervision',
            },
        ),
    ]
