# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0014_teacher_birthdate_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='klass',
            new_name='public',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
    ]
