# Generated by Django 2.0.1 on 2018-07-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0016_populate_corp_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_rpn',
            field=models.CharField(default='', max_length=40),
        ),
    ]
