# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0021_klass_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterUniqueTogether(
            name='corporation',
            unique_together=set([('name', 'city')]),
        ),
    ]
