# Generated by Django 2.2.6 on 2019-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0024_mark_fields_dup'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='has_stages',
            field=models.BooleanField(default=False, verbose_name='Planifie la PP sur ce site'),
        ),
    ]
