# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0002_deposit_date_non_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('room', models.CharField(max_length=20, verbose_name='salle')),
                ('teacher_1', models.CharField(max_length=10, verbose_name='Ens. entretien')),
                ('teacher_2', models.CharField(max_length=10, verbose_name='Ens. dossier')),
                ('status', models.CharField(choices=[('N', 'N'), ('R', 'R'), ('X', 'X')], default='N', max_length=1, verbose_name='satut')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': "Entretien d'admission",
                'verbose_name_plural': "Entretiens d'admission",
            },
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='file_resp',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='interview_resp',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='interview_room',
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='candidats.Interview', verbose_name='entretien'),
        ),
    ]
