# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0003_add_interview_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='certif_of_800h',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='certif_of_cfc',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='proc_admin_ext',
        ),
        migrations.AddField(
            model_name='candidate',
            name='activity_rate',
            field=models.CharField(default='', max_length=50, verbose_name="Taux d'activité"),
        ),
        migrations.AddField(
            model_name='candidate',
            name='certif_800_general',
            field=models.BooleanField(default=False, verbose_name='Attest. 800h. général'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='certif_of_800_childhood',
            field=models.BooleanField(default=False, verbose_name='Attest. 800h. enfance'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='date_convocation_sended',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='diploma',
            field=models.IntegerField(choices=[(0, 'Aucun'), (1, "CFC d'ASE"), (2, 'CFC autre domaine'), (3, 'Matu acad./spéc. ou dipl. ECG'), (4, 'Portfolio')], default=0, verbose_name='Titre sec. II'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='diploma_detail',
            field=models.CharField(default='', max_length=30, verbose_name='Détail titre'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='diploma_status',
            field=models.IntegerField(choices=[(0, 'Inconnu'), (1, 'En cours'), (2, 'Produit')], default=0, verbose_name='Statut titre'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='inscr_other_school',
            field=models.CharField(default='', max_length=30, verbose_name='Inscr. autre école'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_certificate',
            field=models.BooleanField(default=False, verbose_name='Bilan act. prof./dernier stage'),
        ),
    ]
