# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0003_Add_model_Interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='convocation_sended_email',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
