# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0004_complement_ede_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='certif_800_general',
            new_name='certif_of_800_general',
        ),
    ]
