# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0004_send_convocation_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='aes_accords',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'Demander accord du canton concerné'), (2, 'Refus du canton concerné')], default=False, verbose_name='Accord AES'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='residence_permits',
            field=models.IntegerField(choices=[(0, 'Pas nécessaire'), (1, 'Nécessaire - OK'), (2, 'Manquante')], default=0, verbose_name='Autorisation de séjour (pour les personnes étrangères)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='activity_rate',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Taux d'activité"),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='diploma_detail',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Détail titre'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='diploma_status',
            field=models.IntegerField(choices=[(0, 'Inconnu'), (1, 'En cours'), (2, 'OK')], default=0, verbose_name='Statut titre'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='option',
            field=models.CharField(blank=True, choices=[('GEN', 'Généraliste'), ('ENF', 'Enfance'), ('PAG', 'Personnes âgées'), ('HAN', 'Handicap'), ('PE-5400h', 'Parcours Emploi 5400h.'), ('PE-3600h', 'Parcours Emploi 3600h.'), ('PS', 'Parcours stage 5400h.')], max_length=20, verbose_name='Option'),
        ),
    ]
