# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0005_Fix_Candidate_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='convocation_date',
            new_name='date_convocation_mail',
        ),
        migrations.AddField(
            model_name='candidate',
            name='date_validation_mail',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='inscr_other_school',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Inscr. autre école'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='residence_permits',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pas nécessaire'), (1, 'Nécessaire - OK'), (2, 'Manquante')], default=0, verbose_name='Autor. de séjour (pour les pers. étrang.)'),
        ),
    ]
