# Generated by Django 2.0.1 on 2018-06-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0009_remove_total_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='convoc_confirm_receipt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Accusé de réception'),
        ),
    ]
